# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/mail/test?email=1827074175@qq.com

###

GET http://127.0.0.1:8000/auth/code?email=1827074175@qq.com

###

POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "email": "1827074175@qq.com",
  "username": "wzy",
  "password": "123456",
  "confirm_password": "123456",
  "code": "5236"
}

###

POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "1827074175@qq.com",
  "password": "123456"
}

###

### 使用智能体生成名字（已登录）
POST http://127.0.0.1:8000/name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxIiwic3ViIjoiMSIsImV4cCI6MTc3MDI5NDQxNH0.fo2bCd0QyUMoeg7y5HEY4n0zlc61xxNbpSvoU0AG7G0

{
  "surname": "张",
  "length": "两字",
  "gender": "男",
  "other": "尽量大气一点"
}
